import './style.css'

const app = document.querySelector('#app')

app.innerHTML = `
  <div class="jarvis">
      <header class="topbar">
            <div>
                    <span class="status-dot"></span>
                            JARVIS ONLINE
                                  </div>
                                        <div id="clock">--:--:--</div>
                                            </header>

                                                <main class="dashboard">
                                                      <section class="hero">
                                                              <div class="eyebrow">PERSONAL AI SYSTEM</div>
                                                                      <h1>JARVIS</h1>
                                                                              <p>Your personal command center.</p>
                                                                                    </section>

                                                                                          <section class="core">
                                                                                                  <div class="arc"></div>
                                                                                                          <div class="core-circle">
                                                                                                                    <span>J</span>
                                                                                                                            </div>
                                                                                                                                    <div class="core-status" id="status">
                                                                                                                                              SYSTEM READY
                                                                                                                                                      </div>
                                                                                                                                                            </section>

                                                                                                                                                                  <section class="command-panel">
                                                                                                                                                                          <div class="response" id="response">
                                                                                                                                                                                    Hello, Krish. How can I help?
                                                                                                                                                                                            </div>

                                                                                                                                                                                                    <div class="command-row">
                                                                                                                                                                                                              <input
                                                                                                                                                                                                                          id="commandInput"
                                                                                                                                                                                                                                      type="text"
                                                                                                                                                                                                                                                  placeholder="Enter a command..."
                                                                                                                                                                                                                                                              autocomplete="off"
                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                  <button id="sendButton">SEND</button>
                                                                                                                                                                                                                                                                                            <button id="voiceButton">🎙</button>
                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                          </section>
                                                                                                                                                                                                                                                                                                              </main>
                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                `

                                                                                                                                                                                                                                                                                                                const input = document.querySelector('#commandInput')
                                                                                                                                                                                                                                                                                                                const sendButton = document.querySelector('#sendButton')
                                                                                                                                                                                                                                                                                                                const voiceButton = document.querySelector('#voiceButton')
                                                                                                                                                                                                                                                                                                                const response = document.querySelector('#response')
                                                                                                                                                                                                                                                                                                                const status = document.querySelector('#status')
                                                                                                                                                                                                                                                                                                                const clock = document.querySelector('#clock')

                                                                                                                                                                                                                                                                                                                function updateClock() {
                                                                                                                                                                                                                                                                                                                  clock.textContent = new Date().toLocaleTimeString()
                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                  setInterval(updateClock, 1000)
                                                                                                                                                                                                                                                                                                                  updateClock()

                                                                                                                                                                                                                                                                                                                  function jarvis(command) {
                                                                                                                                                                                                                                                                                                                    const text = command.toLowerCase().trim()

                                                                                                                                                                                                                                                                                                                      if (!text) {
                                                                                                                                                                                                                                                                                                                          return 'Please give me a command.'
                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                              if (text.includes('hello') || text.includes('hi')) {
                                                                                                                                                                                                                                                                                                                                  return 'Hello, Krish. Systems are online.'
                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                      if (text.includes('time')) {
                                                                                                                                                                                                                                                                                                                                          return `The current time is ${new Date().toLocaleTimeString()}.`
                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                              if (text.includes('date')) {
                                                                                                                                                                                                                                                                                                                                                  return `Today is ${new Date().toLocaleDateString()}.`
                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                      if (text.includes('youtube')) {
                                                                                                                                                                                                                                                                                                                                                          window.open('https://www.youtube.com', '_blank')
                                                                                                                                                                                                                                                                                                                                                              return 'Opening YouTube.'
                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                  if (text.includes('google')) {
                                                                                                                                                                                                                                                                                                                                                                      window.open('https://www.google.com', '_blank')
                                                                                                                                                                                                                                                                                                                                                                          return 'Opening Google.'
                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                              if (text.includes('who are you')) {
                                                                                                                                                                                                                                                                                                                                                                                  return 'I am JARVIS, your personal command center.'
                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                      return `I received: "${command}". My AI brain is not connected yet.`
                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                      function executeCommand() {
                                                                                                                                                                                                                                                                                                                                                                                        const command = input.value.trim()

                                                                                                                                                                                                                                                                                                                                                                                          if (!command) return

                                                                                                                                                                                                                                                                                                                                                                                            status.textContent = 'PROCESSING...'

                                                                                                                                                                                                                                                                                                                                                                                              setTimeout(() => {
                                                                                                                                                                                                                                                                                                                                                                                                  const answer = jarvis(command)

                                                                                                                                                                                                                                                                                                                                                                                                      response.textContent = answer
                                                                                                                                                                                                                                                                                                                                                                                                          status.textContent = 'SYSTEM READY'

                                                                                                                                                                                                                                                                                                                                                                                                              input.value = ''
                                                                                                                                                                                                                                                                                                                                                                                                                }, 300)
                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                sendButton.addEventListener('click', executeCommand)

                                                                                                                                                                                                                                                                                                                                                                                                                input.addEventListener('keydown', (event) => {
                                                                                                                                                                                                                                                                                                                                                                                                                  if (event.key === 'Enter') {
                                                                                                                                                                                                                                                                                                                                                                                                                      executeCommand()
                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                        })

                                                                                                                                                                                                                                                                                                                                                                                                                        voiceButton.addEventListener('click', () => {
                                                                                                                                                                                                                                                                                                                                                                                                                          const SpeechRecognition =
                                                                                                                                                                                                                                                                                                                                                                                                                              window.SpeechRecognition || window.webkitSpeechRecognition

                                                                                                                                                                                                                                                                                                                                                                                                                                if (!SpeechRecognition) {
                                                                                                                                                                                                                                                                                                                                                                                                                                    response.textContent =
                                                                                                                                                                                                                                                                                                                                                                                                                                          'Voice recognition is not supported in this browser.'
                                                                                                                                                                                                                                                                                                                                                                                                                                              return
                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                  const recognition = new SpeechRecognition()

                                                                                                                                                                                                                                                                                                                                                                                                                                                    recognition.lang = 'en-IN'
                                                                                                                                                                                                                                                                                                                                                                                                                                                      recognition.interimResults = false

                                                                                                                                                                                                                                                                                                                                                                                                                                                        status.textContent = 'LISTENING...'

                                                                                                                                                                                                                                                                                                                                                                                                                                                          recognition.start()

                                                                                                                                                                                                                                                                                                                                                                                                                                                            recognition.onresult = (event) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                const command = event.results[0][0].transcript

                                                                                                                                                                                                                                                                                                                                                                                                                                                                    input.value = command
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        executeCommand()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                            recognition.onerror = () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                status.textContent = 'SYSTEM READY'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    response.textContent = 'I could not hear that. Please try again.'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        recognition.onend = () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            status.textContent = 'SYSTEM READY'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              })